# railway.toml - Railway specific configuration
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables
[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
WEB_CONCURRENCY = "1"
MAX_WORKERS = "1"

---
# Procfile - Process configuration for Railway
web: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 300 --keep-alive 2 --max-requests 100 --max-requests-jitter 10 --preload main:app

---
# requirements.txt - Updated with minimal dependencies
Flask==2.3.3
gunicorn==21.2.0
Pillow==11.3.0
ultralytics==8.3.199
torch==2.8.0
torchvision==0.23.0
opencv-python-headless==4.12.0.88
numpy==2.2.6
requests==2.32.5

---
# runtime.txt - Python version
python-3.11.9

---
# .railwayignore - Files to ignore during deployment
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.venv/
pip-log.txt
pip-delete-this-directory.txt
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.log
.git/
.mypy_cache/
.pytest_cache/
.hypothesis/
.DS_Store
*.sqlite3
*.db